#-----------------------------------------------------------------------------------
#
# An example script for running the Standard Neutrino Beam simulation in G4LBNE
# using a Geant4 generated proton beam. P. Lebrun
#
# Place here the commands that modify the default geometry. 
# We are at Geant4 stage call "PreInit" 
# 
#/LBNE/det/GraphiteTargetLength 840 mm
#/LBNE/det/TargetMaterial Beryllium
#/LBNE/det/TargetLengthOutsideHorn 250 mm
/LBNE/det/construct
#
#exit
/run/initialize
#
# We are at Geant4 stage "idle" 
#
/event/verbose 0
/tracking/verbose 0
#
#
# Primary vertex setting 
#
# Allows the RunID, which is included in the
# output file name(s), to be set at runtime.
#
#/LBNE/stepping/name GeomPropCO108
/LBNE/stepping/generateParticlesFluxThroughHorns TRUE
/LBNE/stepping/filename  /lbne/data/users/lebrun/ThroughHorns/Nominal_1.txt
#/LBNE/stepping/keyVolumeForOutputTo TargetFinVert
#/LBNE/stepping/keyVolumeForOutput TargetUpstrDownstrSegment
#
#
/LBNE/run/setRunID 107
/LBNE/rndm/setRndmSeed 107
#
# If NOT using an external hadron file then this establishes how 
# many particles(protons) to use during the simulation. To be consistent 
# with past neutrino ntuples each run uses 500000 or 100000 protons
#
/LBNE/run/NEvents 100000
/LBNE/output/OutputNtpFileName test2_10k_v3r0p8b_ThroughHonrs_1
#
# This will place Geant4 in the stage "EventProc", i.e. ,simulating events. 
#
/run/beamOn 
#
exit
#
#NOTE: To debug problems grep for "PROBLEM" in the output of the simulation
# "PROBLEM" statements are printed when there is a problem.
#


